version: '3'
services:
  web:
    build: ./folder
    ports:
     - "4000:5000"
    image: "devclubiitd/test1:0.1"
    depends_on:
      - redis
    env_file:
      - ./test.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "in.devclub=Test Flash App 1"
    volumes:
      - type: volume
        source: mydata
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ./folder
        target: /source
        read_only: true
  redis:
    image: "redis:alpine"
restart: unless-stopped
volumes:
    mydata:
      labels:
          - "in.devclub=Test mydata volume"
