version: '3'
services:
  web:
    build: ./folder
    ports:
     - "5000:5000"
    image: "devclubiitd/test1:0.1"
    depends_on:
      - redis
    env_file:
      - ./test.env
  redis:
    image: "redis:alpine"
